name: deploy

on:
  release:
    type: [published]

jobs:
  s3-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - name: install mc
        run: curl -O https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc
      - name: configure mc
        run: './mc config host add scw https://s3.fr-par.scw.cloud  ${{ secrets.SCW_ACCESS_KEY }} ${{ secrets.SCW_SECRET_KEY }} --api S3v4'
      - name: deploy to object storage
        run: ./mc mirror --overwrite --remove --disable-multipart build/ scw/codebench/

  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Porter
        id: download_porter
        run: |2
          name=$(curl -s https://api.github.com/repos/porter-dev/porter/releases/latest | grep "browser_download_url.*/porter_.*_Linux_x86_64\.zip" | cut -d ":" -f 2,3 | tr -d \")
          name=$(basename $name)
          curl -L https://github.com/porter-dev/porter/releases/latest/download/$name --output $name
          unzip -a $name
          rm $name
          chmod +x ./porter
          sudo mv ./porter /usr/local/bin/porter
      - name: Configure Porter
        id: configure_porter
        run: |2
          sudo porter config set-host https://dashboard.getporter.dev
          sudo porter auth login --token ${{secrets.PORTER_TOKEN_1194}}
          sudo porter docker configure
      - name: Docker build, push
        id: docker_build_push
        run: |2
          export $(echo "${{secrets.ENV_FRONT}}" | xargs)
          echo "${{secrets.ENV_FRONT}}" > ./env_porter
          sudo docker build . $(cat ./env_porter | awk 'NF' | sed 's@^@--build-arg @g' | paste -s -d " " -) --file ./Dockerfile -t registry.digitalocean.com/codebench/front-default:$(git rev-parse --short HEAD)
          sudo docker push registry.digitalocean.com/codebench/front-default:$(git rev-parse --short HEAD)
      - name: Deploy on Porter
        id: deploy_porter
        run: |2
          curl -X POST "https://dashboard.getporter.dev/api/webhooks/deploy/${{secrets.WEBHOOK_FRONT}}?commit=$(git rev-parse --short HEAD)"
